# We build our own talkyard-cache image and push to talkyard-cache:$VERSION_TAG, and by
# downloading and using that image, one automatically upgrades the Redis image,
# whenever needed. (So won't need to configure Redis image version, separately, in Prod.)

FROM redis:4.0.9-alpine

