# Configures a server that uses about 1.5G RAM, and to which you can connect a debugger,
# and some passwords.

version: '3.7'
services:
  web:
    #mem_limit: 140M

  app:
    #mem_limit: 700M
    environment:
      PLAY_HEAP_MEMORY_MB: 500
      CREATE_SITE_HOSTNAME: 'localhost'
      E2E_TEST_PASSWORD: 'public'
      FORBIDDEN_PASSWORD: 'public'
      PLAY_SECRET_KEY: 'public-03xP4K463krs4397j923fuyRKB5sek4928674luh49rka5692kj9089'
      POSTGRES_PASSWORD: 'public'
      TY_SYSMAINT_API_SECRET: 'test_sysmaint_api_secret'
      TY_EMAIL_WEBHOOKS_API_SECRET: 'publicEmailWebhooksApiTestSecret'
      TY_FEATURE_FLAGS: 'ffMayPatchSite'
      MAY_FAST_FORWARD_TIME: 'true'

  cache:
    #mem_limit: 30M

  search:
    #mem_limit: 380M
    environment:
      ES_JAVA_OPTS: '-Xms260m -Xmx260m'

  rdb:
    #mem_limit: 140M
    environment:
      POSTGRES_PASSWORD: 'public'

  # A fake external server, for e2e tests, when the Ty server sends its own HTTP
  # requests to external things.
  fakeweb:
    image: ${DOCKER_REPOSITORY}/fakeweb
    restart: always
    # Won't work — we're not in Talkyard's main repo root. Instead, these would-have-
    # been-mounted files are included in the image. [fakeweb_mount_nothing]
    #volumes:
    #  - ./images/fakeweb/app/:/app/:ro
    #  - ./volumes/fakeweb-deno-dir:/deno-dir
    ports:
      # So the Webdriverio e2e tests can ask this server what HTTP requests
      # the Ty server has sent. E.g. outgoing webhooks, or anti spam service queries.
      - '8090:8090'
    networks:
      internal_net:
        ipv4_address: ${INTERNAL_NET_TEST_IP}


  # This won't work; we're in the wrong dir:  [ghost_prod_test_img]
  #it-ghost:
  #  volumes:
  #    - ./tests/int-w/ghost/casper-post.hbs:/var/lib/ghost/current/content/themes/casper/post.hbs
  #  ...
