# Use like so:
#
# d/c -f docker-compose.yml -f docker-compose-no-limits.yml   kill web
# d/c -f docker-compose.yml -f docker-compose-no-limits.yml   rm -f web
# d/c -f docker-compose.yml -f docker-compose-no-limits.yml   build web
# d/c -f docker-compose.yml -f docker-compose-no-limits.yml   up -d web
# d/c -f docker-compose.yml -f docker-compose-no-limits.yml   ps
#

# Don't forget to add default values in the Dockerfile, [0KW2UY3]
# and enable Nginx access_log buffering (nginx.conf).

version: '3.7'
services:
  web:
    environment:
      # Set Nginx limits to high values, useful e.g. when testing performance.
      ED_NGX_LIMIT_CONN_PER_IP: 9001   # max is 65535
      ED_NGX_LIMIT_CONN_PER_SERVER: 9002
      ED_NGX_LIMIT_REQ_PER_IP: 9990030
      ED_NGX_LIMIT_REQ_PER_IP_BURST: 9990040
      ED_NGX_LIMIT_REQ_PER_SERVER: 9990050
      ED_NGX_LIMIT_REQ_PER_SERVER_BURST: 9990060
      ED_NGX_LIMIT_RATE: 9990070k
      ED_NGX_LIMIT_RATE_AFTER: 9990080m
      TY_NGX_ACCESS_LOG_CONFIG: tyalogfmtfast
      TY_NGX_ERROR_LOG_LEVEL: notice
