# We build our own ed-cache image and push to ed-cache:$VERSION_TAG, and by
# downloading and using that image, one automatically upgrades the Redis image,
# whenever needed. (So won't need to configure Redis image version, separately, in Prod.)

FROM redis:3.0.7-alpine

