[package]
name = "paseto-cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pasetors = { version = "0.6.7", features = ["v2"] }

