# Talkyard uses Ubuntu 24.04 ~= Debian 12, and Java 11, currently.
# Could create a Debian slim JRE, see: [slim_jre].
# Cannot upgrade to Java 17, because Nashorn has been removed.


# Build sqlx, for database migrations.
FROM rust:1.91.1-trixie AS rust_img

RUN cargo install sqlx-cli --no-default-features --features native-tls,postgres


# Ubuntu 24.04 LTS (Noble Numbat) uses kernel 6.8, Debian 12 (Bookworm) uses kernel 6.1
# (Debian 11 uses kernel 5.x). Noble ~= Bookwork which we used to build sqlx above.
# (If too different, there tends to be some error like "libc.so.: version `GLIBC_2.32' not found".)
FROM  eclipse-temurin:11.0.29_7-jdk-noble

LABEL org.opencontainers.image.title="Talkyard Dev App" \
      io.talkyard.edition="se" \
      io.talkyard.epoch="1"

COPY --from=rust_img /usr/local/cargo/bin/sqlx     /usr/local/bin/sqlx

# We'll create our own user, 'owner', with the same id as the host OS user.
# But user 'ubuntu', id 1000, often collides with 'owner' (same id),
# so delete it (it's not used for anything, just for convenience, right).
RUN touch /var/mail/ubuntu && chown ubuntu /var/mail/ubuntu && userdel -r ubuntu


RUN \
  apt-get update && \
  apt-get install -y \
  # Diesel needs, otherwise this error:
  #   diesel: error while loading shared libraries: libpq.so.5:
  #      cannot open shared object file: No such file or directory
  #libpq-dev  \
  # Required:
  # (git needed so can include Git revision in the build,
  # and show at http://server/-/build-info.)
  curl unzip git \
  # For PASETO v2.local tokens, needs XChaCha20Poly1305:
  libsodium-dev \
  # Nice to have:
  tree less wget net-tools bash \
  # For 'ps':
  procps \
  # tput, needed by Coursier somehow
  #ncurses \
  # Telnet, nice for troubleshooting SMTP problems for example.
  telnet
  #busybox-extras

# ADD extracts tar archives; this .tgz gets unpacked at /opt/sbt/{bin/,conf/}.
ADD  sbt/sbt-1.11.7.tgz  /opt/

# Install 'gosu' so we can use it instead of 'su'.
# For unknown reasons, '  exec su ...' no longer works, but 'exec gosu ...' works fine.
# Edit: Not in use, see  entrypoint.dev.sh  [su_or_gosu].
#       Also, this is old, for Alpine:  [alp_2_deb]
#RUN apk add --no-cache \
#  --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ \
#  gosu

# Play's HTTP and HTTPS listen ports, Java debugger port, JMX port 3333.
EXPOSE 9000 9443 9999 3333

# Docker volumes talkyard-v1-pub-files and -priv-files get mounted here.
# (We create sub dirs as needed from Scala code. [pub_files_volume])
RUN mkdir -p /opt/talkyard/pub-files/ && \
    mkdir -p /opt/talkyard/priv-files/
    # We'll chown to the correct user in entrypoint.dev.sh — but right
    # now, here, we don't yet know the id of that user.
    ## In dev builds, we don't know the id of the user we'll start Talkyrad as, so let
    ## anyone write to these dirs. (In prod builds, we chown to appuser, instead.)
    ##chmod -R ugo+rw /opt/talkyard/pub-files/ && \
    ##chmod -R ugo+rw /opt/talkyard/priv-files/

# Add a self signed dummy cert for the dummy SMTP server (the 'fakemail' Docker container),
# so one can test connecting to it with TLS and see if the TLS conf vals work. [26UKWD2]
# ("changeit" = default keystore password)
# This is for Alpine. What do in Debian instead? [alp_2_deb]
#COPY fakemail-publ-test-self-signed.crt /smtp-server.crt
#RUN cd $JAVA_HOME/jre/lib/security && \
#    keytool -keystore cacerts -storepass changeit -noprompt -trustcacerts \
#        -importcert -alias ldapcert -file /smtp-server.crt

WORKDIR /opt/talkyard/app/

RUN \
    # Add Java to $PATH not just for root, but for user 'owner' too — that's the
    # user that calls Java and starts Ty.
    sed --in-place 's#^PATH="#PATH="/opt/java/openjdk/bin:#' /etc/environment && \
    echo 'JAVA_HOME=/opt/java/openjdk\n'          >>         /etc/environment

# Don't do until now, so won't need to rebuild whole image if editing entrypoint.
COPY entrypoint.dev.sh /docker-entrypoint.sh
RUN  chmod ugo+x   /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

# Overriden in docker-compose.yml
ENV PLAY_HEAP_MEMORY_MB 2048



# ------------------------------------------------------------
# SBT options, as of 2020-12-20:  (d/c exec app bash ; cd /opt/sbt/bin ; ./sbt -h)
# ------------------------------------------------------------
# Usage: sbt [options]
#
#   -h | --help         print this message
#   -v | --verbose      this runner is chattier
#   -V | --version      print sbt version information
#   --numeric-version   print the numeric sbt version (sbt sbtVersion)
#   --script-version    print the version of sbt script
#   -d | --debug        set sbt log level to debug
#   -debug-inc | --debug-inc
#                       enable extra debugging for the incremental debugger
#   --no-colors         disable ANSI color codes
#   --color=auto|always|true|false|never
#                       enable or disable ANSI color codes      (sbt 1.3 and above)
#   --supershell=auto|always|true|false|never
#                       enable or disable supershell            (sbt 1.3 and above)
#   --traces            generate Trace Event report on shutdown (sbt 1.3 and above)
#   --timings           display task timings report on shutdown
#   --sbt-create        start sbt even if current directory contains no sbt project
#   --sbt-dir   <path>  path to global settings/plugins directory (default: ~/.sbt)
#   --sbt-boot  <path>  path to shared boot directory (default: ~/.sbt/boot in 0.11 series)
#   --ivy       <path>  path to local Ivy repository (default: ~/.ivy2)
#   --mem    <integer>  set memory options (default: 1024)
#   --no-share          use all local caches; no sharing
#   --no-global         uses global caches, but does not use global ~/.sbt directory.
#   --jvm-debug <port>  Turn on JVM debugging, open at the given port.
#   --batch             disable interactive mode
#
#   # sbt version (default: from project/build.properties if present, else latest release)
#   --sbt-version  <version>   use the specified version of sbt
#   --sbt-jar      <path>      use the specified jar as the sbt launcher
#
#   # java version (default: java from PATH, currently openjdk version "1.8.0_212")
#   --java-home <path>         alternate JAVA_HOME
#
#   # jvm options and output control
#   JAVA_OPTS           environment variable, if unset uses "-Dfile.encoding=UTF-8"
#   .jvmopts            if this file exists in the current directory, its contents
#                       are appended to JAVA_OPTS
#   SBT_OPTS            environment variable, if unset uses ""
#   .sbtopts            if this file exists in the current directory, its contents
#                       are prepended to the runner args
#   /etc/sbt/sbtopts    if this file exists, it is prepended to the runner args
#   -Dkey=val           pass -Dkey=val directly to the java runtime
#   -J-X                pass option -X directly to the java runtime
#                       (-J is stripped)
#   -S-X                add -X to sbt's scalacOptions (-S is stripped)
#
# In the case of duplicated or conflicting options, the order above
# shows precedence: JAVA_OPTS lowest, command line options highest.
# ------------------------------------------------------------


# Set Java's user.home env var to /home/owner so sbt will cache downloads there, [SBTHOME]
# more specifically, in /home/owner/.cache/coursier/.
# Although user.home is set in entrypoint.sh, apparently that setting gets lost here —
# sbt then downloads things to /root/.sbt and /root/.ivy2 if running as root inside a vm.
# Maybe because of 'exec'?
#
CMD \
 cd /opt/talkyard/app/ && \
 #
 # Apply any new database migrations in ./migrations/.
 # Let's call from Play instead?! Play can show an error web page, if migration failed [flyway_2_sqlx]
 # And Play knows if we want the _test database.
 # /usr/local/bin/sqlx migrate run --database-url postgres://postgres:public@rdb/diesel_testdb2 && \
 #
 # Start the app server (sbt, a Scala build tool, will start Play Framework).
 exec /opt/sbt/bin/sbt \
  --mem $PLAY_HEAP_MEMORY_MB \
  -J-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9999 \
  # Avoid SBT compilation java.lang.StackOverflowError in
  # scala.tools.nsc.transform.Erasure.
  -J-Xss30m \
  -Duser.home=/home/owner \
   # see [30PUK42] in app-prod/Dockerfile
  -Djava.security.egd=file:/dev/./urandom \
  -Dcom.sun.management.jmxremote.port=3333 \
  -Dcom.sun.management.jmxremote.ssl=false \
  -Dcom.sun.management.jmxremote.authenticate=false \
  -Dhttp.port=9000 \
  -Dhttps.port=9443 \
  # [PROTOCONF]
  -Dhttps.protocols=TLSv1.3,TLSv1.2 \
  -Djdk.tls.client.protocols=TLSv1.3,TLSv1.2 \
  # Otherwise ignored, although as per the docs it should be found since it's on the classpath.
  -Dlogback.configurationFile=/opt/talkyard/app/conf/logback.xml \
  # log4j2 problem, disable this:
  -Dlog4j2.formatMsgNoLookups=true \
  #
  -Dconfig.file=/opt/talkyard/app/conf/app-dev.conf \
  run

