
# ----- Download Deno ----------------------------------------------------

# For now, we're running Deno in the app container, together with the app server
# (Play Framework),   because  there's no way to easily add a new container for
# running Deno, to Talkyard open source installations. — But there will be, in
# tech stack v1. Then, we'll run Deno in its own container instead.  [ty_v1]
# (We use Deno for rendering pages, since Nashorn has been removed from
# JDK 17+ [no_nashorn].)

# Downloading Deno (below) is based on:
#    https://github.com/denoland/deno_docker/blob/main/bin.dockerfile

# 1.34.3 is latest, as of 2023-06-19.
ARG DENO_VERSION=1.34.3

## Just reuse whatever image we use for the app server (below) so no need
## to download a different image?
# FROM buildpack-deps:20.04-curl AS deno_download — no, different.
FROM  eclipse-temurin:11.0.18_10-jdk-focal AS deno_download

RUN export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install -y unzip \
  && rm -rf /var/lib/apt/lists/*

ARG DENO_VERSION
RUN curl -fsSL https://github.com/denoland/deno/releases/download/v${DENO_VERSION}/deno-x86_64-unknown-linux-gnu.zip \
    --output deno.zip \
  && unzip deno.zip \
  && rm deno.zip \
  && chmod 755 deno


# ----- App server -------------------------------------------------------


# Scala supports Java 8, 11 and 17. Ty uses Debian 11 and Java 11, currently.
# Cannot upgrade to Java 17, because Nashorn has been removed. [no_nashorn]

# This is Ubuntu though. Could create a Debian 11 slim JRE, see: [slim_jre].
FROM  eclipse-temurin:11.0.18_10-jdk-focal

# Don't:
#     eclipse-temurin:11.0.17_8-jdk-jammy
#
# — then there can be a misleading "insufficient memory" error, because Ubuntu 22
# (JDK-Jammy) ships with glibc 2.35, which uses clone3 (>= 2.34 does),
# but Docker doesn't work with clone3, until PR 42681 (fix for 42680). Which
# is available starting with Docker v20.10.10, but I'd rather not force people
# to upgrade their Docker installation. (Debian 11 should be ok too, doesn't use clone3.)
# See:
#  A misleading "insufficient memory for the Java Runtime [...]" error:
#  https://stackoverflow.com/questions/72841549/container-fails-to-start-insufficient-memory-for-the-java-runtime-environment-t/73970043#73970043
#
# https://github.com/adoptium/containers/issues/215#issuecomment-1142046045
#
# via:  https://stackoverflow.com/questions/74443957/insufficient-memory-while-running-eclipse-temurin17-jdk-docker-image
# via:  https://www.google.com/search?q=Failed+to+start+thread+%22GC+Thread%230%22+-+pthread_create+failed+(EPERM)+for+attributes%3A+stacksize%3A+1024k%2C+guardsize%3A+4k%2C+detached.&oq=Failed+to+start+thread+%22GC+Thread%230%22+-+pthread_create+failed+(EPERM)+for+attributes%3A+stacksize%3A+1024k%2C+guardsize%3A+4k%2C+detached.&aqs=chrome..69i57.1225j0j1&sourceid=chrome&ie=UTF-8
#
#
# (Also see:  https://docs.docker.com/engine/security/seccomp/ )
#
# Email about some clone3 wrapper:
# https://sourceware.org/git/?p=glibc.git;a=commit;h=d8ea0d0168b190bdf138a20358293c939509367f
#
# Anyway, to upgr Docker, if needed:
#
# How to:  https://docs.docker.com/engine/install/ubuntu/
# That is:  "To upgrade Docker Engine, follow the installation instructions", which is just:  (and this worked)
#
#     sudo apt-get update
#     sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
#


ARG DENO_VERSION
ENV DENO_VERSION=${DENO_VERSION}

COPY --from=deno_download /deno /usr/local/bin/deno


RUN \
  apt-get update && \
  apt-get install -y \
  # Required:
  # (git needed so can include Git revision in the build,
  # and show at http://server/-/build-info.)
  curl unzip git \
  # For PASETO v2.local tokens, needs XChaCha20Poly1305:
  libsodium-dev \
  # Nice to have:
  tree less wget net-tools bash \
  # For 'ps':
  procps \
  # tput, needed by Coursier somehow
  #ncurses \
  # Telnet, nice for troubleshooting SMTP problems for example.
  telnet
  #busybox-extras

# ADD extracts tar archives; this .tgz gets unpacked at /opt/sbt/{bin/,conf/}.
ADD  sbt/sbt-1.4.5.tgz  /opt/

# Install 'gosu' so we can use it instead of 'su'.
# For unknown reasons, '  exec su ...' no longer works, but 'exec gosu ...' works fine.
# Edit: Not in use, see  entrypoint.dev.sh  [su_or_gosu].
#       Also, this is old, for Alpine:  [alp_2_deb]
#RUN apk add --no-cache \
#  --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ \
#  gosu

# Play's HTTP and HTTPS listen ports, Java debugger port, JMX port 3333.
EXPOSE 9000 9443 9999 3333

RUN mkdir -p /opt/talkyard/uploads/ && \
    chmod -R ugo+rw /opt/talkyard/uploads/

# Add a self signed dummy cert for the dummy SMTP server (the 'fakemail' Docker container),
# so one can test connecting to it with TLS and see if the TLS conf vals work. [26UKWD2]
# ("changeit" = default keystore password)
# This is for Alpine. What do in Debian instead? [alp_2_deb]
#COPY fakemail-publ-test-self-signed.crt /smtp-server.crt
#RUN cd $JAVA_HOME/jre/lib/security && \
#    keytool -keystore cacerts -storepass changeit -noprompt -trustcacerts \
#        -importcert -alias ldapcert -file /smtp-server.crt

WORKDIR /opt/talkyard/app/

RUN \
    # Add Java to $PATH not just for root, but for user 'owner' too — that's the
    # user that calls Java and starts Ty.
    sed --in-place 's#^PATH="#PATH="/opt/java/openjdk/bin:#' /etc/environment && \
    echo 'JAVA_HOME=/opt/java/openjdk\n'          >>         /etc/environment

# Don't do until now, so won't need to rebuild whole image if editing entrypoint.
COPY entrypoint.dev.sh /docker-entrypoint.sh
RUN  chmod ugo+x   /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

# Overriden in docker-compose.yml
ENV PLAY_HEAP_MEMORY_MB 2048



# ------------------------------------------------------------
# SBT options, as of 2020-12-20:  (d/c exec app bash ; cd /opt/sbt/bin ; ./sbt -h)
# ------------------------------------------------------------
# Usage: sbt [options]
#
#   -h | --help         print this message
#   -v | --verbose      this runner is chattier
#   -V | --version      print sbt version information
#   --numeric-version   print the numeric sbt version (sbt sbtVersion)
#   --script-version    print the version of sbt script
#   -d | --debug        set sbt log level to debug
#   -debug-inc | --debug-inc
#                       enable extra debugging for the incremental debugger
#   --no-colors         disable ANSI color codes
#   --color=auto|always|true|false|never
#                       enable or disable ANSI color codes      (sbt 1.3 and above)
#   --supershell=auto|always|true|false|never
#                       enable or disable supershell            (sbt 1.3 and above)
#   --traces            generate Trace Event report on shutdown (sbt 1.3 and above)
#   --timings           display task timings report on shutdown
#   --sbt-create        start sbt even if current directory contains no sbt project
#   --sbt-dir   <path>  path to global settings/plugins directory (default: ~/.sbt)
#   --sbt-boot  <path>  path to shared boot directory (default: ~/.sbt/boot in 0.11 series)
#   --ivy       <path>  path to local Ivy repository (default: ~/.ivy2)
#   --mem    <integer>  set memory options (default: 1024)
#   --no-share          use all local caches; no sharing
#   --no-global         uses global caches, but does not use global ~/.sbt directory.
#   --jvm-debug <port>  Turn on JVM debugging, open at the given port.
#   --batch             disable interactive mode
#
#   # sbt version (default: from project/build.properties if present, else latest release)
#   --sbt-version  <version>   use the specified version of sbt
#   --sbt-jar      <path>      use the specified jar as the sbt launcher
#
#   # java version (default: java from PATH, currently openjdk version "1.8.0_212")
#   --java-home <path>         alternate JAVA_HOME
#
#   # jvm options and output control
#   JAVA_OPTS           environment variable, if unset uses "-Dfile.encoding=UTF-8"
#   .jvmopts            if this file exists in the current directory, its contents
#                       are appended to JAVA_OPTS
#   SBT_OPTS            environment variable, if unset uses ""
#   .sbtopts            if this file exists in the current directory, its contents
#                       are prepended to the runner args
#   /etc/sbt/sbtopts    if this file exists, it is prepended to the runner args
#   -Dkey=val           pass -Dkey=val directly to the java runtime
#   -J-X                pass option -X directly to the java runtime
#                       (-J is stripped)
#   -S-X                add -X to sbt's scalacOptions (-S is stripped)
#
# In the case of duplicated or conflicting options, the order above
# shows precedence: JAVA_OPTS lowest, command line options highest.
# ------------------------------------------------------------


# Set Java's user.home env var to /home/owner so sbt will cache downloads there, [SBTHOME]
# more specifically, in /home/owner/.cache/coursier/.
# Although user.home is set in entrypoint.sh, apparently that setting gets lost here —
# sbt then downloads things to /root/.sbt and /root/.ivy2 if running as root inside a vm.
# Maybe because of 'exec'?
#
CMD \
 cd /opt/talkyard/app/ && \
 exec /opt/sbt/bin/sbt \
  --mem $PLAY_HEAP_MEMORY_MB \
  -J-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9999 \
  # Avoid SBT compilation java.lang.StackOverflowError in
  # scala.tools.nsc.transform.Erasure.
  -J-Xss30m \
  -Duser.home=/home/owner \
   # see [30PUK42] in app-prod/Dockerfile
  -Djava.security.egd=file:/dev/./urandom \
  -Dcom.sun.management.jmxremote.port=3333 \
  -Dcom.sun.management.jmxremote.ssl=false \
  -Dcom.sun.management.jmxremote.authenticate=false \
  -Dhttp.port=9000 \
  -Dhttps.port=9443 \
  # SSL has security flaws. Use TLS instead. [NOSSL] [PROTOCONF]
  -Ddeployment.security.SSLv2Hello=false \
  -Ddeployment.security.SSLv3=false \
  -Dhttps.protocols=TLSv1.1,TLSv1.2 \
  -Djdk.tls.client.protocols=TLSv1.1,TLSv1.2 \
  # Otherwise ignored, although as per the docs it should be found since it's on the classpath.
  -Dlogback.configurationFile=/opt/talkyard/app/conf/logback.xml \
  # log4j2 problem, disable this:
  -Dlog4j2.formatMsgNoLookups=true \
  #
  -Dconfig.file=/opt/talkyard/app/conf/app-dev.conf \
  run

