#!/bin/bash

# Go to the project directory (whih is the parent directory).
script_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $script_dir
cd ..

# cli = comman line interface. That is, starts a prompt where you can type
# things like 'clean', 'test', 'compile', 'run', 'dist', 'console'.

# (Don't start nginx — apparently it won't find the app container, because the app
# container is here started with 'run' (not 'up') I would think, so it doesn't
# get the correct network address ? )

docker-compose run --rm --service-ports app /opt/typesafe-activator/bin/activator \
  -jvm-debug 9999 \
  -Dcom.sun.management.jmxremote.port=3333 \
  -Dcom.sun.management.jmxremote.ssl=false \
  -Dcom.sun.management.jmxremote.authenticate=false \
  -Dhttp.port=9000 \
  -Dhttps.port=9443 \
  "$@"

