#!/bin/bash

# To download a specific Chromedriver version: (e.g. v 2.38)
#   s/selenium-install --drivers.chrome.version=2.38

node_modules/selenium-standalone/bin/selenium-standalone install --config=s/selenium-config.js $@

