#!/bin/bash

for x in {1..9}
do
  if [ -f "$1" ]; then
    break
  fi
  sleep 1
  echo "Waiting for transpilation of Typescript to Javascript, file missing: $1"
done

./node_modules/webdriverio/bin/wdio $@
exit_code=$?

if [ $exit_code -ne 0 ]; then
  echo
  echo "Error. E2E test failed, exit code: $exit_code"
fi

echo
exit $exit_code
