#!/bin/bash

# These tests need Nodejs 14. Newer versions don't support Webdriverio's synchronous mode.
#
# Let's run the e2e tests first with Nodejs 22, then Nodejs 14. We'll have to return
# exit code 0 here then, if is v22 not v14.  Otherwise (if returning 1) we'd fail
# the test suite, or we'd need to rewrite  s/run-e2e-tests quite a lot?
# This is simpler:   [e2e_nodejs_old_v14]
#
node_ver=$(node --version)
if [[ "$node_ver" == v14.* ]]; then
  : # Correct version — run the tests.
elif [[ "$node_ver" == v22.* ]]; then
  echo "Skipping this test — it needs Nodejs v14, but now we're using $node_ver."
  exit 0
else
  echo "Totally unexpected Nodejs version. Is: $node_ver, should be v14 (or v22)."
  exit 1
fi


cd tests/e2e/


# [E2EHTTPS]
# This is old Webdriver 6, since we're in tests/e2e/ not e2e-wdio7/.  [wdio_6_to_7]
cmd="node_modules/.bin/wdio  wdio.conf.js  $@"
echo
echo "NODE_TLS_REJECT_UNAUTHORIZED=0  $cmd"
echo
NODE_TLS_REJECT_UNAUTHORIZED=0  $cmd
exit_code=$?

if [ $exit_code -ne 0 ]; then
  echo
  echo
  echo "Error. E2E test failed, exit code: $exit_code"
  echo
  echo "Was started like so:"
  echo "    NODE_TLS_REJECT_UNAUTHORIZED=0  $cmd"
fi

echo
exit $exit_code
