#!/bin/bash

cd tests/e2e/


# [E2EHTTPS]
cmd="../../node_modules/.bin/wdio  wdio.conf.js  $@"
echo
echo "NODE_TLS_REJECT_UNAUTHORIZED=0  $cmd"
echo
NODE_TLS_REJECT_UNAUTHORIZED=0  $cmd
exit_code=$?

if [ $exit_code -ne 0 ]; then
  echo
  echo
  echo "Error. E2E test failed, exit code: $exit_code"
  echo
  echo "Was started like so:"
  echo "    NODE_TLS_REJECT_UNAUTHORIZED=0  $cmd"
fi

echo
exit $exit_code
