# We build our own talkyard-proxy image and push to talkyard-proxy:$VERSION_TAG, so that by
# downloading and using that image, one automatically uses the right version of Traefik.

FROM traefik:v1.7.6-alpine
