
= The Talkyard World



== Different types of "Posts"

In Talkyard, pages and replies are "posts":

Forum Post = new forum discussion page, a.k.a. thread, or Original Post.
Forum Reply = A reply to a forum post.

Forum intro post = Shown at the top of the forum post index page
and explains what the forum is about. Can be collapsed.

Blog Post = blog article.
Blog Comment = a reply to a blog article.

Wiki Page = a wiki page.
Wiki Comment = a comment on a wiki page.


== Three kinds of pages

Index pages a.k.a. site section pages: Currently only of type Forum,
to list forum topics. Later, maybe Wiki main pages too, or Blog post index pages.

Description pages: Meta pages that describes categories and tags and their purposes.

Topic pages: The actual contents in the community. E.g. ideas, questions,
open-ended discussions. Or articles or documentation. — The things end users
visit the community for.

Index pages and description pages are just there to help the end users
find the actual topic pages.

Source code wise, each page has a `PageType` field with values like
Forum or Blog — if it's an index page. Or Question, Idea, Discussion etc
— if it's a (discussion) topic page.


=== Index pages

(A.k.a. site section pages.)
There's just one index page type, currently, namely forum topi list pages.
Later there'll be a Wiki section page type too? Or even a Blog
section page type but probably static HTML blogs are better — or Ty could
have an API for exporting a blog section page to static HTML or CommonMark,
then discussing via embedded comments. Similar to exporting from, say,
WordPress to static HTML.

Maybe optional per user feed page(s) in the future.


=== Description pages

When in a forum category, click Edit Category, then Edit Description
to see the category description page.

Or about user texts (bios), or tag descriptions.


=== Topic pages

E.g. questions, ideas, problems, discussions, documentation articles.

Questions can be answered / solved.

Ideas and Problems can be solved too: a reply selected as
e.g. a problem solution.  `[tpc_typ_solv]`
Or they can have their doing status
toggled from discussing (triage) to planned, doing, done — without any particular
reply selected as a solution.

There're three kinds of topic types: Outside-In, Inside-Out, and Discussions:

==== Outside-In

Pepole outside the organization make feature requests, report problems,
post questions to the organization and each other. These types:

- Questions: How do I do this?
- Problems (bug reports): This seems broken, can you fix?
- Ideas, e.g. feature requests.

(If you use Ty for internal support, the ones posting Outside-In
topics would be your co-workers, not customers.)

==== Inside-Out

The organization writes something, and publishes for their
audience to read. E.g. a company publishes a blog article, or help docs,
or an announcement, for their customers and users to read. These types:

- Announcements (for existing customers about new features)
- Documentation (for existing customers about how to use already existing features)
- Articles (e.g. blog articles for attracting new customers)

==== Discussions

People both in and outside the organization discuss something. These types:

- Discussion: open-ended discussion, typically there's no single best answer.
- Embedded comments, e.g. discussing a blog posts.
- Link pages: For just posting a link and discussing it, like at Reddit or HackerNews.
  Slightly makes Talkyard work like a news aggregator.



== Forum post statuses




== Vote types


All vote types enabled by default, but Disagree can be disabled  [tyworld_5mj98267]
— some people wanted to not have any Disagree votes, but they were
ok with the other votes — just the Like vote, plus Bury and Unwanted for staff,
and optionally Do-It and Do-Not votes.

=== Do-It votes, Do-Not votes and Like votes

Admins can enable Do-It and, optionally, Do-Not votes of topics,
in categories of their choice.
And, optionally, let people do-it(-not) vote directly from the topic list page.

This can 1) make Talkyard work like a news aggregator with vote buttons that
moves a news topic up, or down. (Do and Do-Not then means
"do show this higher up in the news items list" or "do not show higher up").
And can 2) make Ty work like an idea voting tool,
where you can see the number of votes, and also vote,
directly from the question or feature ideas lists — A Do-It vote then means
"Yes, do implement this idea".

These votes are called Do-it (and Do-Not) votes, instead of "upvotes",
because "upvote" would be ambigious — could also refer to a Like vote.

==== Do-It votes and Like votes

Do-It votes and Like votes, can work independenttly of each other,
if the admins want. (Not yet implemented.)
For example, you can Do-Not vote on an idea, and at the same time
Like vote the _description_ of the idea
— in case you like the way the idea was presented,
although you might think it's too off-topic (so you Do-Not voted it).

Maybe this can make a Talkyard communtiy feel extra friendly, when although
someone's idea got Do-Not votes and won't happen, there might still be some
Like votes of the _description_ of the idea, making the idea submitter feel
welcomend although the idea got rejected.

But if Do-It votes and Like votes were the same, it wouldn't be possible to
both Do-Not and Like vote a topic (because that'd mean Do-Not and yes-Do-It
votes at the same time by the same person).

Also, maybe in the future maybe each person would get a certain number of Do-It
votes to distribute among all ideas, and hen could add many votes to the
same idea. — Everyone got, say, 10, Do-It votes to distribute among all ieas /
feature requests.
And you could add, say, 3 Do-It votes to a feature that was really important
to you. For this to work, it makes sense to keep Like votes and Do-It votes separate.
(Ty would then show both how many Do-It votes an idea got, _and_ from how many
different people.) — This not implemented.

=== Upvotes and Downvotes

There isn't any single specific "upvote" or "downvote" in Talkyard.

You might say that Do-It and, optionally, Do-Not votes are upvotes and downvotes.
They don't affect people's karma — they're only for indicating how the community
wants to prioritize things.

Or you might say that Like votes and Unwanted votes are upvotes and downvotes.
They affect the post author's karma.

Disagree and Bury votes are not meant as downvotes. Disagreeing isn't
inherently negative, and a Bury voted reply might just be a welcomed "Thanks" or "Me too"
that the staff wanted to move downwards (curating the discussion).
— In fact, something people disagree a bit about, can be more interesting,
than something everyone agrees about? [tywd_disagree_fine]


== Categories and permissions


=== Sub category permissions

If moving a publicly visible category S to another category B, so that S becomes
a sub category of B, then, in Talkyard, category S won't be any more visible than B.
Anything else would be unexpected: People (incl I) assume that if base category B
is access restricted, then sub cats in B, are, they too.  `[see_sub_cat]`

(Later, maybe maybe there could be a "power admin" feature to optionally allow access
to sub categories, although the base category is access restricted. [power_admin]
Let's say an organizaiton creates a category for a project, and invites external
collaborators to post questions and ideas in a sub category — but the org people
don't want the external people to see the base category.  But the people in the org
still think it's nice to have everything-related-to-the-project in the same category.
Or maybe this'd be better implemented as sub sub cats?
Proj Base Cat: { Proj Private: ...Private sub-sub cats, Proj Ext: ...pub sub-sub cats })

Only may-Not-see is inherited in the category tree — other cat perms, e.g.
may-post-topics, are not inherited; instead, are configured per category.
Maybe it'd be nice if may-edit-wiki permissions got inherited?  Or if, when adding
a sub category, or editing the base category perms, one could apply the base
category settings to the sub cats  `[propagate_cat_perms]`  (instead of inheriting).




== Embedded comments

A Talkyard discussion can be embedded below a blog post, as a blog comments section.
And on other types of web pages, for discussing other things.

There can be many comments iframes, on the same embedding page.
So, for example, a page showing different items in a shop, on the same page,
can have small comment sections about each item, below the item,
simultaneously on the same page, e.g. to show the most popular customer comments
about each item. Could be combined with a button to expand the comments or
maybe go to a full screen discussion page about that item.


=== Lazy pages

[emb_lzy_pgs]
Each iframe with comments, is backed by a Talkyard discussion page of
type PageType.EmbeddedComments. Such a Talkyard page isn't created
before it's needed — that is, when the first comment gets posted,
or someone clicks Like (then, the like vote needs a page id),
or the blog visitor configures a notify-me-of-comments notification level
for that blog post discussion.

// first comment gets posted (or like vote or notf setting changed).
// So, a draft for the very first comment, usually won't have any page id.)