
= The Talkyard World

Domain model.



== Different types of "Posts"

In Talkyard, pages and replies are "posts":

Forum Post = new forum discussion page, a.k.a. thread, or Original Post.
Forum Reply = A reply to a forum post.

Forum intro post = Shown at the top of the forum post index page
and explains what the forum is about. Can be collapsed.

Blog Post = blog article.
Blog Comment = a reply to a blog article.

Wiki Page = a wiki page.
Wiki Comment = a comment on a wiki page.


== Three kinds of pages

Index pages a.k.a. site section pages: Currently only of type Forum,
to list forum topics. Later, maybe Wiki main pages too, or Blog post index pages.

Description pages: Meta pages that describes categories and tags and their purposes.

Topic pages: The actual contents in the community. E.g. ideas, questions,
open-ended discussions. Or articles or documentation. — The things end users
visit the community for.

Index pages and description pages are just there to help the end users
find the actual topic pages.

Source code wise, each page has a `PageType` field with values like
Forum or Blog — if it's an index page. Or Question, Idea, Discussion etc
— if it's a (discussion) topic page.


=== Index pages

(A.k.a. site section pages.)
There's just one index page type, currently, namely forum topi list pages.
Later there'll be a Wiki section page type too? Or even a Blog
section page type but probably static HTML blogs are better — or Ty could
have an API for exporting a blog section page to static HTML or CommonMark,
then discussing via embedded comments. Similar to exporting from, say,
WordPress to static HTML.

Maybe optional per user feed page(s) in the future.


=== Description pages

When in a forum category, click Edit Category, then Edit Description
to see the category description page.

Or about user texts (bios), or tag descriptions.


=== Topic pages

E.g. questions, ideas, problems, discussions, documentation articles.

Questions can be answered / solved.

Ideas and Problems can be solved too: a reply selected as
e.g. a problem solution.  `[tpc_typ_solv]`
Or they can have their doing status
toggled from discussing (triage) to planned, doing, done — without any particular
reply selected as a solution.

There're three kinds of topic types: Outside-In, Inside-Out, and Discussions:

==== Outside-In

Pepole outside the organization make feature requests, report problems,
post questions to the organization and each other. These types:

- Questions: How do I do this?
- Problems (bug reports): This seems broken, can you fix?
- Ideas, e.g. feature requests.

(If you use Ty for internal support, the ones posting Outside-In
topics would be your co-workers, not customers.)

==== Inside-Out

The organization writes something, and publishes for their
audience to read. E.g. a company publishes a blog article, or help docs,
or an announcement, for their customers and users to read. These types:

- Announcements (for existing customers about new features)
- Documentation (for existing customers about how to use already existing features)
- Articles (e.g. blog articles for attracting new customers)

==== Discussions

People both in and outside the organization discuss something. These types:

- Discussion: open-ended discussion, typically there's no single best answer.
- Embedded comments, e.g. discussing a blog posts.
- Link pages: For just posting a link and discussing it, like at Reddit or HackerNews.
  Slightly makes Talkyard work like a news aggregator.



== Forum post statuses




== Vote types


All vote types enabled by default, but Disagree can be disabled  [tyworld_5mj98267]
— some people wanted to not have any Disagree votes, but they were
ok with the other votes — just the Like vote, plus Bury and Unwanted for staff.




== Categories and permissions


=== Sub category permissions

If moving a publicly visible category S to another category B, so that S becomes
a sub category of B, then, in Talkyard, category S won't be any more visible than B.
Anything else would be unexpected: People (incl I) assume that if base category B
is access restricted, then sub cats in B, are, they too.  `[see_sub_cat]`

(Later, maybe maybe there could be a "power admin" feature to optionally allow access
to sub categories, although the base category is access restricted. [power_admin]
Let's say an organizaiton creates a category for a project, and invites external
collaborators to post questions and ideas in a sub category — but the org people
don't want the external people to see the base category.  But the people in the org
still think it's nice to have everything-related-to-the-project in the same category.
Or maybe this'd be better implemented as sub sub cats?
Proj Base Cat: { Proj Private: ...Private sub-sub cats, Proj Ext: ...pub sub-sub cats })

Only may-Not-see is inherited in the category tree — other cat perms, e.g.
may-post-topics, are not inherited; instead, are configured per category.
Maybe it'd be nice if may-edit-wiki permissions got inherited?  Or if, when adding
a sub category, or editing the base category perms, one could apply the base
category settings to the sub cats  `[propagate_cat_perms]`  (instead of inheriting).
