/// <reference path="../test-types.ts"/>

import * as _ from 'lodash';
import assert = require('assert');
import fs = require('fs');
import server = require('../utils/server');
import utils = require('../utils/utils');
import pages = require('../utils/pages');
import pagesFor = require('../utils/pages-for');
import settings = require('../utils/settings');
import make = require('../utils/make');
import logAndDie = require('../utils/log-and-die');
import c = require('../test-constants');

declare let browser: any;

let everyonesBrowsers;
let owen;
let owensBrowser;
let strangersBrowser;

let idAddress: IdAddress;
let siteId: any;

const mariasCommentOne = 'mariasCommentOne';
const mariasCommentTwo = 'mariasCommentTwo';
const mariasCommentThree = 'mariasCommentThree';

const localHostname = 'comments-for-e2e-test-embdscid-localhost-8080';
const embeddingOrigin = 'http://e2e-test-embdscid.localhost:8080';
const pageAaaSlug = 'emb-cmts-aaa.html';


describe("emb cmts forum intro tour for admins  TyT6AKBR2044", () => {

  it("initialize people", () => {
    everyonesBrowsers = _.assign(browser, pagesFor(browser));
    owensBrowser = everyonesBrowsers;
    owen = make.memberOwenOwner();
  });

  it("import a site", () => {
    const site: SiteData = make.forumOwnedByOwen('embftour', { title: "Emb Cmts Forum Tour Test" });
    site.meta.localHostname = localHostname;
    site.settings.allowEmbeddingFrom = embeddingOrigin;
    site.settings.showCategories = false;

    // TESTS_MISSING create a site from scratch. Break out & reuse code from 
    // embedded-comments-create-site-no-verif-email-admin-area-tour.2browsers.test.ts ?

    idAddress = server.importSiteData(site);
    siteId = idAddress.id;
  });

  it("create an embedding page aaa", () => {
    const dir = 'target';
    fs.writeFileSync(`${dir}/${pageAaaSlug}`, makeHtml());
  });


  function makeHtml(): string {
    return `
<html>
<head>
<title>Embedded comments E2E test</title>
</head>
<body>
<p>Embedded comments E2E test page, for emb cmts forum intro tour<br>
Ok to delete. The comments: ("long ago" generated by the admin js bundle [5AKBST03])
</p>

<script>talkyardCommentsServerUrl='http://${localHostname}.localhost';</script>
<script async defer src="http://${localHostname}.localhost/-/talkyard-comments.js"></script>
<div class="talkyard-comments" data-discussion-id="" style="margin-top: 45px;">

<p>/End of page.</p>
</body>
</html>`;
  }

  it("Owen goes to the topic list", () => {
    owensBrowser.go(idAddress.origin);
    owensBrowser.tour.runToursAlthoughE2eTest();
  });

  it("... logs in", () => {
    owensBrowser.complex.loginWithPasswordViaTopbar(owen);
  });

  it("An intro tour appears", () => {
    owensBrowser.tour.assertTourStarts(true);
  });

  it("... Owen views the tour", () => {
    console.log('Step 1');
    owensBrowser.tour.clickNextForStepNr(1);
    console.log('Step 2');
    owensBrowser.tour.clickNextForStepNr(2);
    console.log('Step 3');
    owensBrowser.tour.clickNextForStepNr(3);
    console.log('Step 4');
    owensBrowser.tour.clickNextForStepNr(4);
    console.log('Step 5');
    browser.waitAndClick('.esAvtrName_name');
  });

  it("... but skips last steps 6 and 7. So tour won't get marked as seen [TyT2ABKRT05]", () => {
    // Noop.
  });

  it("Owen goes to the forum", () => {
    owensBrowser.go(embeddingOrigin + '/' + pageAaaSlug);
  });

  it("... adds a comment, so a page gets created", () => {
    owensBrowser.complex.replyToEmbeddingBlogPost("Text text text");
  });

  it("... then back to the topic list", () => {
    owensBrowser.go(idAddress.origin);
  });

  it("The intro tour appears again (since he didn't finish watching it)", () => {
    owensBrowser.tour.assertTourStarts(true);
  });

  it("... Owen views the tour", () => {
    console.log('Step 1');
    owensBrowser.tour.clickNextForStepNr(1);
    console.log('Step 2');
    owensBrowser.tour.clickNextForStepNr(2);
    console.log('Step 3');
    owensBrowser.tour.clickNextForStepNr(3);
    console.log('Step 4');
    owensBrowser.tour.clickNextForStepNr(4);
    console.log('Step 5');
    browser.waitAndClick('.esAvtrName_name');
  });

  it("... all steps, this time", () => {
    console.log('Step 6');
    owensBrowser.tour.clickNextForStepNr(6);
  });

  it("Now the tour won't start again", () => {
    owensBrowser.refresh();  // beacon-saves tourTipsSeen
    // Here, the tour would restart, but ...
    owensBrowser.refresh();  // reloads up-to-date tourTipsSeen
    owensBrowser.tour.assertTourStarts(false);
  });

});

